package:
  name: jplephem
  version: "2.5"

source:
  fn: jplephem-2.5.tar.gz
  url: https://pypi.python.org/packages/source/j/jplephem/jplephem-2.5.tar.gz
  md5: 2880f4a443cbc3ec3c9d90a9bc8e7d22

build:
  number: 1

requirements:
  build:
    - python

  run:
    - python
    - numpy

test:
  # Python imports
  imports:
    - jplephem

about:
  home: https://pypi.python.org/pypi/jplephem
  license: MIT License
  summary: 'Python version of NASA DE4xx ephemerides, the basis for the 
Astronomical Alamanac'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
